#!/usr/bin/env python3
# Regenerate the "What people said" section of README.md from the curated
# kudos file on the site. Run by .github/workflows/oss-stats.yml alongside
# update_oss_stats.py; safe to run by hand.
#
# Everything between the KUDOS markers is replaced. Nothing else is touched.
#
# The quotes are hand-curated rather than scraped. A sentiment filter over
# comment threads would eventually lift a line out of context or quote
# criticism as praise, and this text goes on a public profile. The single
# source of truth is assets/kudos.json in the github.io repository, fetched
# here so the site and the profile cannot drift apart.

from __future__ import annotations

import json
import os
import re
import sys
import urllib.error
import urllib.request
from pathlib import Path

USER = os.environ.get("OSS_STATS_USER", "basil-k-aji-dev")
README = Path(__file__).resolve().parent.parent / "README.md"
START = "<!-- KUDOS:START -->"
END = "<!-- KUDOS:END -->"

KUDOS_URL = os.environ.get(
    "KUDOS_URL",
    f"https://raw.githubusercontent.com/{USER}/{USER}.github.io/main/assets/kudos.json",
)

# How many to show. The rest stay on the site; a profile README that scrolls
# for a page of quotations reads as bragging rather than evidence.
MAX_SHOWN = 5


def fetch_kudos() -> list[dict]:
    request = urllib.request.Request(
        KUDOS_URL, headers={"User-Agent": f"{USER}-kudos"}
    )
    with urllib.request.urlopen(request, timeout=30) as response:
        payload = json.loads(response.read().decode("utf-8"))
    entries = payload.get("kudos", [])
    if not isinstance(entries, list):
        raise ValueError("kudos.json: 'kudos' is not a list")
    return entries


def one_line(text: str) -> str:
    """Collapse to a single line and escape what would break a table cell."""
    return " ".join(str(text).split()).replace("|", "\\|")


def build_section(entries: list[dict]) -> str:
    lines = [
        START,
        "",
        "<!-- Generated by scripts/update_kudos.py via .github/workflows/oss-stats.yml.",
        "     Quotes are curated by hand in assets/kudos.json on the site, not scraped.",
        "     Edits between these markers are overwritten. -->",
        "",
    ]

    if not entries:
        lines += ["", END]
        return "\n".join(lines)

    for entry in entries[:MAX_SHOWN]:
        author = one_line(entry.get("author", ""))
        role = one_line(entry.get("role", ""))
        repo = one_line(entry.get("repo", ""))
        context = one_line(entry.get("context", ""))
        url = entry.get("url", "")
        badge = f" · _{role}_" if role else ""
        where = f"[{repo}]({url})" if url else repo
        lines += [
            f"> {one_line(entry.get('quote', ''))}",
            ">",
            f"> — **[@{author}](https://github.com/{author})**{badge}, on {where}"
            + (f" — {context}" if context else ""),
            "",
        ]

    remaining = len(entries) - MAX_SHOWN
    tail = (
        f"<sub>Quoted verbatim from public pull request threads; an ellipsis marks "
        f"omitted text. "
        + (
            f"[{remaining} more on my site]"
            f"(https://{USER}.github.io/contributions.html#kudos)."
            if remaining > 0
            else f"[More on my site](https://{USER}.github.io/contributions.html#kudos)."
        )
        + "</sub>"
    )
    lines += [tail, "", END]
    return "\n".join(lines)


def main() -> int:
    original = README.read_text(encoding="utf-8")
    if START not in original or END not in original:
        print(f"markers not found in {README}; add {START} / {END} first", file=sys.stderr)
        return 1

    try:
        entries = fetch_kudos()
    except (urllib.error.URLError, ValueError, json.JSONDecodeError) as exc:
        # Leaving the previous section in place beats replacing real quotations
        # with an error, so a transient fetch failure is not a build failure.
        print(f"could not fetch {KUDOS_URL}: {exc}; leaving the section as-is", file=sys.stderr)
        return 0

    section = build_section(entries)
    updated = re.sub(
        re.escape(START) + r".*?" + re.escape(END),
        lambda _: section,
        original,
        flags=re.DOTALL,
    )

    if updated == original:
        print("no change")
        return 0
    README.write_text(updated, encoding="utf-8")
    print(f"README.md updated — {min(len(entries), MAX_SHOWN)} of {len(entries)} quotes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
