#!/usr/bin/env python3
# Regenerate the "Open Source Contributions" section of README.md from the
# GitHub search API. Run by .github/workflows/oss-stats.yml; safe to run by
# hand with GH_TOKEN set.
#
# Everything between the OSS-STATS markers is replaced. Nothing else in the
# README is touched.

from __future__ import annotations

import json
import os
import re
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path

USER = os.environ.get("OSS_STATS_USER", "basil-k-aji-dev")
README = Path(__file__).resolve().parent.parent / "README.md"
START = "<!-- OSS-STATS:START -->"
END = "<!-- OSS-STATS:END -->"
TOP_N = 10
BAR_WIDTH = 22

# Own repos are not "contributions to open source" in the sense this section
# claims, so they are excluded from the leaderboard. Set to "0" to include.
EXCLUDE_OWN = os.environ.get("OSS_STATS_EXCLUDE_OWN", "1") != "0"


def search(query: str, *, per_page: int = 100, pages: int = 10) -> dict:
    """GitHub issue search, following pagination up to `pages`."""
    token = os.environ.get("GH_TOKEN") or os.environ.get("GITHUB_TOKEN")
    headers = {
        "Accept": "application/vnd.github+json",
        "User-Agent": f"{USER}-oss-stats",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    if token:
        headers["Authorization"] = f"Bearer {token}"

    total = 0
    items: list[dict] = []
    for page in range(1, pages + 1):
        url = "https://api.github.com/search/issues?" + urllib.parse.urlencode(
            {"q": query, "per_page": per_page, "page": page}
        )
        request = urllib.request.Request(url, headers=headers)
        for attempt in range(4):
            try:
                with urllib.request.urlopen(request, timeout=30) as response:
                    payload = json.loads(response.read().decode("utf-8"))
                break
            except urllib.error.HTTPError as exc:
                # Search is rate limited separately (30/min authenticated) and
                # answers 403/429 when exceeded. Back off rather than writing a
                # half-empty section over good content.
                if exc.code in (403, 429) and attempt < 3:
                    time.sleep(5 * (attempt + 1))
                    continue
                raise
        total = payload.get("total_count", 0)
        batch = payload.get("items", [])
        items.extend(batch)
        if len(items) >= total or not batch:
            break
    return {"total": total, "items": items}


def repo_of(item: dict) -> str:
    return item.get("repository_url", "").replace("https://api.github.com/repos/", "")


def bar(count: int, peak: int) -> str:
    if peak <= 0:
        return ""
    filled = max(1, round(count / peak * BAR_WIDTH)) if count else 0
    return "█" * filled


def build_section() -> str:
    merged = search(f"is:pr author:{USER} is:merged")
    open_prs = search(f"is:pr author:{USER} is:open")
    everything = search(f"is:pr author:{USER}")

    per_repo: dict[str, dict[str, int]] = {}
    shown = {"merged": 0, "open": 0}
    for bucket, items in (("merged", merged["items"]), ("open", open_prs["items"])):
        for item in items:
            name = repo_of(item)
            if not name:
                continue
            if EXCLUDE_OWN and name.lower().startswith(f"{USER.lower()}/"):
                continue
            per_repo.setdefault(name, {"merged": 0, "open": 0})[bucket] += 1
            shown[bucket] += 1

    ranked = sorted(
        per_repo.items(),
        key=lambda kv: (-(kv[1]["merged"] + kv[1]["open"]), -kv[1]["merged"], kv[0].lower()),
    )[:TOP_N]
    peak = max((v["merged"] + v["open"] for _, v in ranked), default=0)

    lines = [
        START,
        "",
        "<!-- Generated by scripts/update_oss_stats.py via .github/workflows/oss-stats.yml.",
        "     Edits between these markers are overwritten. -->",
        "",
        f"![Merged](https://img.shields.io/badge/Merged-{shown['merged']}-2ea043?style=for-the-badge&logo=github&logoColor=white)",
        f"![In review](https://img.shields.io/badge/In%20review-{shown['open']}-1f6feb?style=for-the-badge&logo=github&logoColor=white)",
        f"![Repositories](https://img.shields.io/badge/Repositories-{len(per_repo)}-6e7681?style=for-the-badge&logo=github&logoColor=white)",
        "",
    ]

    if ranked:
        lines += [
            "**Where I contribute most**",
            "",
            "| # | Repository | Merged | In review | |",
            "|--:|---|--:|--:|---|",
        ]
        for position, (name, counts) in enumerate(ranked, start=1):
            total = counts["merged"] + counts["open"]
            lines.append(
                f"| {position} | [{name}](https://github.com/{name}) "
                f"| {counts['merged']} | {counts['open']} | `{bar(total, peak)}` {total} |"
            )
        lines.append("")

    lines += [
        f"<sub>Auto-updated {time.strftime('%Y-%m-%d')} · GitHub search API · "
        + (
            f"contributions to other people's repositories only "
            f"({everything['total']} PRs in total including my own repos)"
            if EXCLUDE_OWN
            else f"{everything['total']} PRs in total"
        )
        + "</sub>",
        "",
        END,
    ]
    return "\n".join(lines)


def main() -> int:
    original = README.read_text(encoding="utf-8")
    section = build_section()

    if START in original and END in original:
        updated = re.sub(
            re.escape(START) + r".*?" + re.escape(END),
            lambda _: section,
            original,
            flags=re.DOTALL,
        )
    else:
        print(f"markers not found in {README}; add {START} / {END} first", file=sys.stderr)
        return 1

    if updated == original:
        print("no change")
        return 0
    README.write_text(updated, encoding="utf-8")
    print("README.md updated")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
